version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.8
  github: haskell-works/github-release@1.3.3
  hackage: haskell-works/hackage@1.4.2
  merge-point: haskell-works/merge-point@1.0.0

commands:
  build-librdkafka:
    description: Build librdkafka
    steps:
      - restore_cache:
          key: cache--{{ .Environment.CACHE_VERSION }}--librdkafka--{{ checksum "scripts/build-librdkafka" }}
      - run:
          name: Build librdkafka
          command: ./scripts/build-librdkafka
      - save_cache:
          key: cache--{{ .Environment.CACHE_VERSION }}--librdkafka--{{ checksum "scripts/build-librdkafka" }}
          paths: .librdkafka

workflows:
  build-app-pipelines:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          before-build: [build-librdkafka]
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          before-build: [build-librdkafka]
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.8.3
          executor: haskell/ghc-8_8_3
          before-build: [build-librdkafka]
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.10.2
          executor: haskell/ghc-8_10_2
          before-build: [build-librdkafka]
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - merge-point/merge-point:
          name: Build Ok
          requires:
            - GHC 8.4.4
            - GHC 8.6.5
            - GHC 8.8.3
            - GHC 8.10.2

      - github/release-cabal:
          name: GitHub Release
          context: haskell-ci
          requires:
            - Build Ok
          checkout: true
          filters:
            branches:
              only: master

      - hackage/upload:
          publish: true
          requires:
            - GitHub Release
          username: ${HACKAGE_USER}
          password: ${HACKAGE_PASS}
          filters:
            branches:
              only: master
